/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobileshopeesystem;
import com.datastax.driver.core.Cluster;
import com.datastax.driver.core.ResultSet;
import com.datastax.driver.core.Row;
import com.datastax.driver.core.Session;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author TEJU
 */
public class customerinfo extends javax.swing.JFrame {
Cluster cluster = Cluster.builder().addContactPoint("127.0.0.1").build();
    Session session=cluster.connect();
    public Welcome w = new Welcome();
   public String select;
   public String username;
   public static String getname,getmobile,getadds,getemail,getmodel;
   public static int getprice,getqty;
    
    
    public customerinfo(DisplayMob d,Welcome ww) throws IOException {
        initComponents();
         select=d.selectphone;
       username=ww.uname1;
        System.out.println("username "+select);
                System.out.println("username "+ww.uname1);
        String q="select name from reg where uname='"+username+"';";
        Session s4=cluster.connect("mobiledata");
    		ResultSet rs=s4.execute(q);
    		String s=rs.all().toString().replace("Row[","").replace("[[", "").replace("]]", "").replaceAll(" ", "").replace("[", "");
                System.out.println("name"+s);
                nametext.setText(s);
        String q1="select mobile from reg where uname='"+username+"';";  
        ResultSet rs1=s4.execute(q1);
        String s1=rs1.all().toString().replace("Row[","").replace("[[", "").replace("]]", "").replaceAll(" ", "").replace("[", "");
        System.out.println("mobile "+s1);
        mobiletext.setText(s1);
        
        String qqq="select address from reg where uname='"+username+"';";
        ResultSet rs2=s4.execute(qqq);
    	String add=rs2.all().toString().replace("Row[","").replace("[[", "").replace("]]", "").replaceAll(" ", "").replace("[", "");
        System.out.println("address"+add);
        addresstext.setText(add);
        
        String q3="select email from reg where uname='"+username+"';";
        ResultSet rs3=s4.execute(q3);
    	String s3=rs3.all().toString().replace("Row[","").replace("[[", "").replace("]]", "").replaceAll(" ", "").replace("[", "");
        System.out.println("email"+s3);
        emailtext.setText(s3);
        
       String q4="select model_no from mobiledetails where model_no='"+select+"';";
        ResultSet rs4=s4.execute(q4);
    	String s5=rs4.all().toString().replace("Row[","").replace("[[", "").replace("]]", "").replaceAll(" ", "").replace("[", "");
        System.out.println("model no"+s4);
        modeltext.setText(s5);
        
        String q6="select price from mobiledetails where model_no='"+select+"';";
        ResultSet rs6=s4.execute(q6);
    	String s6=rs6.all().toString().replace("Row[","").replace("[[", "").replace("]]", "").replaceAll(" ", "").replace("[", "");
        System.out.println("price"+s6);
        pricetext.setText(s6);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        mobiletext = new javax.swing.JTextField();
        addresstext = new javax.swing.JTextField();
        emailtext = new javax.swing.JTextField();
        modeltext = new javax.swing.JTextField();
        pricetext = new javax.swing.JTextField();
        quantitytext = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(107, 98, 35, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Mobile no");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(107, 153, 60, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(107, 209, 49, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Email");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(107, 270, 35, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText(" Model");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(107, 337, 41, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Price");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(107, 404, 55, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Enter Quantity");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(107, 459, 110, 17);
        getContentPane().add(nametext);
        nametext.setBounds(315, 97, 165, 30);

        mobiletext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiletextActionPerformed(evt);
            }
        });
        getContentPane().add(mobiletext);
        mobiletext.setBounds(315, 152, 165, 30);

        addresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstextActionPerformed(evt);
            }
        });
        getContentPane().add(addresstext);
        addresstext.setBounds(315, 208, 165, 30);
        getContentPane().add(emailtext);
        emailtext.setBounds(315, 269, 165, 30);
        getContentPane().add(modeltext);
        modeltext.setBounds(315, 336, 165, 30);
        getContentPane().add(pricetext);
        pricetext.setBounds(315, 393, 165, 30);
        getContentPane().add(quantitytext);
        quantitytext.setBounds(315, 448, 165, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Check Your Details");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 20, 184, 29);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(120, 500, 110, 23);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);
        cancelButton.setBounds(330, 500, 110, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileshopee/backgroung.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 650, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mobiletextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiletextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobiletextActionPerformed

    private void addresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstextActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_addresstextActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
    try {
        // TODO add your handling code here:
         getname=  nametext.getText().toString();
        getmobile= mobiletext.getText().toString();
         getadds= addresstext.getText().toString();
         getemail= emailtext.getText().toString();
        getmodel= modeltext.getText().toString();
         getprice= Integer.parseInt(pricetext.getText());
         getqty= Integer.parseInt(quantitytext.getText());
        
        System.out.println("price  =="+getprice);
        System.out.println("qty== "+getqty);
        int id1=0;
        Session s2=cluster.connect("mobiledata");//connect to keyspace
        String maxid="select max(id) as max_id from customerpurchase;";
        ResultSet r= s2.execute(maxid);
        System.out.println("result return"+r);
        while(!r.isExhausted())
        {
            Row row=r.one();
            id1=row.getInt("max_id");
            id1++;
            System.out.println("id1 "+id1);
        }
        
        
        String q3="insert into customerpurchase(id,name,mobile,address,email,model_no,price,qty) values("
                +id1+",'"+getname+"','"+getmobile+"','"+getadds+"','"+getemail+"','"+getmodel+"',"+getprice+","+getqty+");";
        
        s2.execute(q3);
        
        String tableqty="select qty from mobiledetails where model_no='"+select+"'";
        ResultSet rs=s2.execute(tableqty);
        int s=Integer.parseInt(rs.all().toString().replace("Row[","").replace("[[", "").replace("]]", "").replaceAll(" ", "").replace("[", ""));
        System.out.println("quantity: "+s);
        
        int newqty= s-getqty;
        System.out.println("new Quantity"+newqty);
        
        String upqty="update mobiledetails set qty="+newqty+" where model_no='"+select+"';";
        s2.execute(upqty);
        
        setVisible(false);
        Buy n=new Buy(this);
        n.setVisible(true);
    } catch (Exception ex) {
        Logger.getLogger(customerinfo.class.getName()).log(Level.SEVERE, null, ex);
    }
             
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
    try {
        // TODO add your handling code here:
        setVisible(false);
        DisplayMob n=new DisplayMob();
        n.setVisible(true);
    } catch (Exception ex) {
        Logger.getLogger(customerinfo.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new customerinfo(new DisplayMob(),new Welcome()).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(customerinfo.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(customerinfo.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addresstext;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField emailtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobiletext;
    private javax.swing.JTextField modeltext;
    private javax.swing.JTextField nametext;
    private javax.swing.JTextField pricetext;
    private javax.swing.JTextField quantitytext;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
