/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mobileshopeesystem;

import com.datastax.driver.core.Cluster;
import com.datastax.driver.core.ResultSet;
import com.datastax.driver.core.Session;
import static com.kenai.jnr.x86asm.Asm.sp;
import java.util.Arrays;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import static jnr.x86asm.Asm.sp;

/**
 *
 * @author divya_000
 */
public class DisplayMobile extends javax.swing.JFrame {
 Cluster cluster = Cluster.builder().addContactPoint("127.0.0.1").build();
    Session session=cluster.connect();
   public String selectphone="";
    /**
     * Creates new form DisplayMobile
     */
    public DisplayMobile() {
        initComponents();
        /*String q4="select * from mobiledetails;";
              Session s3=cluster.connect("mobiledata");
              ResultSet rs= s3.execute(q4);
              System.out.println(rs.all());
              //jTextField1.setText(rs.all();
              //jTable1.setModel(null);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        availablebutton = new javax.swing.JButton();
        modelenter = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        okbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Available Mobiles");

        availablebutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        availablebutton.setText("Available Mobiles");
        availablebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availablebuttonActionPerformed(evt);
            }
        });

        modelenter.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        modelenter.setText("Enter Model No u want to purchase");

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Samsung galaxy S8", "Samsung galaxy on8", "Samsung Galaxy Grand", "Samsun Galaxy s3", "Moto g4", "Moto g5 plus", "Moto e3", "Moto g plus", "Samsung on7 pro", "Vivo v5", "Vivo y211", "Intex aqua q7n", "Micromax Canvas Nitro", "Oppo a37", "Honor holly2", "Lava iris fuel", "Lava a97", "Coolpad Mega", "Coolpad note5" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        okbutton.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        okbutton.setText("OK");
        okbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(modelenter, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(availablebutton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(okbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(availablebutton)
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelenter)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addComponent(okbutton)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void availablebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availablebuttonActionPerformed
        // TODO add your handling code here:
        Cluster cluster = Cluster.builder().addContactPoint("127.0.0.1").build();
    		Session s4=cluster.connect("mobiledata");
    		
    		//String value1=tf25.getText();
    		
    		
    		
    		String q5="select * from mobiledetails;";
    		ResultSet rs=s4.execute(q5);
    		String s=rs.all().toString().replace("Row[","[");
    		//String result1=result.replace("]","");
    		//String result2=result.replace("[","");
    		String row;
    	    System.out.println(s);
    	    
    		//String result=rs.all().toString().substring(5).replace("]", "");
    	/*  char[] resArr=result2.toCharArray();
    	  int counter=0;
    	  for(int i=0;i<resArr.length;i++)
    	  {
    		  if(resArr[i]!='[' && resArr[i]!=']')
    		  {
    			  if(resArr[i]==','){
    			  counter++;
    			  }
    		  }
    	  }
    	  System.out.println("ccccccccccccc"+counter);
    	  */
    	    
    	 // Split on this delimiter
    	    String[] rows = s.split("], \\[");
    	    for (int i = 0; i < rows.length; i++) {
    	        // Remove any beginning and ending braces and any white spaces
    	        rows[i] = rows[i].replace("[[", "").replace("]]", "").replaceAll(" ", "");
    	    }

    	    // Get the number of columns in a row
    	    int numberOfColumns = rows[0].split(",").length;

    	    // Setup your matrix
    	    String[][] matrix = new String[rows.length][numberOfColumns];

    	    // Populate your matrix
    	    for (int i = 0; i < rows.length; i++) {
    	        matrix[i] = rows[i].split(",");
    	    }
    	    // Display your matrix
    	    System.out.println(Arrays.deepToString(matrix));
    	    
    	    
            JFrame f = new JFrame("Table Example");  
              
                            String column[]={ " model_no","bcamera","color","compnay","fcamera","imei_no","os","price","processor","qty","ram","storage"};         
                           // String column[]={"ID","NAME","SALARY"};         
                            
                           // final JTable jt=new JTable(data,column);    
                            final JTable jt=new JTable(matrix,column);    
                            
                            jt.setCellSelectionEnabled(true);  
            ListSelectionModel select= jt.getSelectionModel();  
            select.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
            select.addListSelectionListener(new ListSelectionListener() {  
              public void valueChanged(ListSelectionEvent e) {  
                String Data = null;  
                int[] row = jt.getSelectedRows();  
                int[] columns = jt.getSelectedColumns();  
                for (int i = 0; i < row.length; i++) {  
                  for (int j = 0; j < columns.length; j++) {  
                    Data = (String) jt.getValueAt(row[i], columns[j]);  
                  } }  
                System.out.println("Table element selected is: " + Data);    
              }       

           // @Override
           // public void valueChanged(ListSelectionEvent e) {
           //     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           // }
            });
            JScrollPane sp=new JScrollPane(jt);    
            f.add(sp);  
            f.setSize(300, 200);  
            f.setVisible(true);

    }//GEN-LAST:event_availablebuttonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
       selectphone=jComboBox1.getSelectedItem().toString();
        System.out.println("select"+selectphone);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void okbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okbuttonActionPerformed
        // TODO add your handling code here:
        
        
         String q5="select * from mobiledetails where model_no='"+selectphone+"';";
                Session s4=cluster.connect("mobiledata");
    		ResultSet rs=s4.execute(q5);
                String s=rs.all().toString().replace("Row[","[");
    		String row;
    	    //System.out.println(s);
    	    
    	    
    	 // Split on this delimiter
    	    String[] rows = s.split("], \\[");
    	    for (int i = 0; i < rows.length; i++) {
    	        // Remove any beginning and ending braces and any white spaces
    	        rows[i] = rows[i].replace("[[", "").replace("]]", "").replaceAll(" ", "");
    	    }

    	    // Get the number of columns in a row
    	    int numberOfColumns = rows[0].split(",").length;

    	    // Setup your matrix
    	    String[][] matrix = new String[rows.length][numberOfColumns];

    	    // Populate your matrix
    	    for (int i = 0; i < rows.length; i++) {
    	        matrix[i] = rows[i].split(",");
    	    }
            
    	    // Display your matrix
            
    	    System.out.println(Arrays.deepToString(matrix));
    	    for (int i = 0; i <rows.length ; i++) {System.out.println("\n");
                for (int j = 0; j < numberOfColumns; j++) {
                    System.out.println("\t"+matrix[i][j]);
                }
        }
    	    
            JFrame f = new JFrame("Table Example");  
             String column[]={ " model_no","bcamera","color","compnay","fcamera","imei_no","os","price","processor","qty","ram","storage"};         
                           final JTable jt=new JTable(matrix,column);    
                            
                            jt.setCellSelectionEnabled(true);  
            ListSelectionModel select1= jt.getSelectionModel();  
            select1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);  
            select1.addListSelectionListener(new ListSelectionListener() {  
              public void valueChanged(ListSelectionEvent e) {  
                String Data = null;  
                int[] row = jt.getSelectedRows();  
                int[] columns = jt.getSelectedColumns();  
                for (int i = 0; i < row.length; i++) {  
                  for (int j = 0; j < columns.length; j++) {  
                    Data = (String) jt.getValueAt(row[i], columns[j]);  
                  } }  
                System.out.println("Table element selected is: " + Data);    
              }       

           // @Override
           // public void valueChanged(ListSelectionEvent e) {
           //     throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
           // }
            });
            JScrollPane sp=new JScrollPane(jt);    
            f.add(sp);  
            f.setSize(500, 200);  
            f.setVisible(true);
        
        
        
        
        
        
    		/*
                setVisible(false);
                             Details n=new Details(this);
                            n.setVisible(true);
                */
    }
//GEN-LAST:event_okbuttonActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//new DisplayMobile();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayMobile().setVisible(true);
               // new customerinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton availablebutton;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel modelenter;
    private javax.swing.JButton okbutton;
     //private javax.swing.JButton cbutton;
    // End of variables declaration//GEN-END:variables
}
