package mobileshopeesystem;
import com.datastax.driver.core.Cluster;
import com.datastax.driver.core.Session;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Registration extends javax.swing.JFrame {
 Cluster cluster = Cluster.builder().addContactPoint("127.0.0.1").build();
    Session session=cluster.connect();
    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        formname = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        uname = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        nametext = new javax.swing.JTextField();
        mobiletext = new javax.swing.JTextField();
        emailtext = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addresstext = new javax.swing.JTextArea();
        unametext = new javax.swing.JTextField();
        passtext = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        cancelbutton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        name.setText("Name");
        getContentPane().add(name);
        name.setBounds(133, 99, 63, 17);

        formname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        formname.setText("Registration form");
        getContentPane().add(formname);
        formname.setBounds(206, 31, 218, 28);

        mobile.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mobile.setText("Mobile No");
        getContentPane().add(mobile);
        mobile.setBounds(133, 144, 84, 17);

        email.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        email.setText("Email-Id");
        getContentPane().add(email);
        email.setBounds(133, 190, 93, 17);

        address.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        address.setText("Address");
        getContentPane().add(address);
        address.setBounds(133, 256, 81, 17);

        uname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        uname.setText("Username");
        getContentPane().add(uname);
        uname.setBounds(133, 310, 93, 17);

        pass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pass.setText("Password");
        getContentPane().add(pass);
        pass.setBounds(133, 362, 93, 17);
        getContentPane().add(nametext);
        nametext.setBounds(372, 98, 151, 20);

        mobiletext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiletextActionPerformed(evt);
            }
        });
        getContentPane().add(mobiletext);
        mobiletext.setBounds(372, 143, 151, 20);

        emailtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailtextActionPerformed(evt);
            }
        });
        getContentPane().add(emailtext);
        emailtext.setBounds(372, 189, 151, 20);

        addresstext.setColumns(20);
        addresstext.setRows(5);
        jScrollPane1.setViewportView(addresstext);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(372, 238, 151, 35);

        unametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unametextActionPerformed(evt);
            }
        });
        getContentPane().add(unametext);
        unametext.setBounds(374, 307, 149, 20);
        getContentPane().add(passtext);
        passtext.setBounds(374, 361, 149, 20);

        submitbutton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submitbutton);
        submitbutton.setBounds(181, 421, 112, 25);

        cancelbutton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cancelbutton.setText("SignUp");
        cancelbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelbutton);
        cancelbutton.setBounds(345, 421, 112, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mobileshopee/backgroung.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 650, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbuttonActionPerformed
     try {
         // TODO add your handling code here:
         setVisible(false);
         Welcome n=new Welcome();
         n.setVisible(true);
     } catch (IOException ex) {
         Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_cancelbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
        
         String name = this.nametext.getText().toString();
         String mobile = this.mobiletext.getText().toString();
         String email = this.emailtext.getText().toString();
         String address = this.addresstext.getText().toString();
         String uname  = this.unametext.getText().toString();
         String pass = this.passtext.getText().toString();
         Session s2=cluster.connect("mobiledata");//connect to keyspace
            String q3="insert into reg(name,mobile,email,address,uname,pass) values('"
                    +name+"','"+mobile+"','"+email+"','"+address+"','"+uname+"','"+pass+"');";
                    
            s2.execute(q3);
            System.out.println("Data Inserted Sucessfully");
         nametext.setText("");
         mobiletext.setText("");
         emailtext.setText("");
         addresstext.setText("");
         unametext.setText("");
         passtext.setText("");
         
         setVisible(false);
                             
     try {
         Welcome n;
         n = new Welcome();
         n.setVisible(true);
     } catch (Exception ex) {
         Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
     }
                            
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void mobiletextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiletextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobiletextActionPerformed

    private void emailtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailtextActionPerformed

    private void unametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unametextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unametextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextArea addresstext;
    private javax.swing.JButton cancelbutton;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailtext;
    private javax.swing.JLabel formname;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobile;
    private javax.swing.JTextField mobiletext;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel pass;
    private javax.swing.JTextField passtext;
    private javax.swing.JButton submitbutton;
    private javax.swing.JLabel uname;
    private javax.swing.JTextField unametext;
    // End of variables declaration//GEN-END:variables
}
